---
# Source: runtime-docker/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-docker
  namespace: default
  labels:
    helm.sh/chart: runtime-docker-0.1.0
    app.kubernetes.io/name: runtime-docker
    app.kubernetes.io/instance: runtime-docker
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    app:
      endpoint: unix:///var/run/arhat.sock
      log:
      - file: stderr
        format: console
        level: verbose
      tls:
        caCert: /path/to/caCert
        cert: /path/to/client-cert
        enabled: false
        insecureSkipVerify: true
        key: /path/to/client-cert-key
---
# Source: runtime-docker/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: runtime-docker
  namespace: default
  labels:
    helm.sh/chart: runtime-docker-0.1.0
    app.kubernetes.io/name: runtime-docker
    app.kubernetes.io/instance: runtime-docker
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: runtime-docker
      app.kubernetes.io/instance: runtime-docker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runtime-docker
        app.kubernetes.io/instance: runtime-docker
    spec:
      securityContext:
        {}
      tolerations:
        - key: arhat.dev/namespace
          value: default
        - key: node.kubernetes.io/unschedulable
          operator: Exists
      containers:
        - name: arhat-peripheral
          securityContext:
            {}
          image: "ghcr.io/arhat-ext/runtime-docker:latest"
          imagePullPolicy: IfNotPresent
          command:
            - /runtime-docker
            - -c
            - /etc/runtime-docker/config.yaml
          # ports:
          #   - name: http
          #     containerPort: 80
          #     protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: config
              mountPath: /etc/runtime-docker
          resources:
            {}
      nodeSelector:
        arhat.dev/namespace: default
      volumes:
        - name: config
          configMap:
            name: runtime-docker
